import json
B=lambda s,d,c,i,w,h:dict(str=s,dex=d,con=c,int=i,wis=w,cha=h)
SEAS=dict(str=-1,dex=-1,con=-1,int=1,wis=1,cha=1)
WRIT="**Lieutenant's Writ (R1, extended to lieutenants):** Shadow Jump 40 ft/day, shadow to shadow (Su), through Nightwind attunement."
EE="Evening's Edge gloves (claws 1d6, finesse; armor bonus overlapped by the suit), hand crossbow with drow sleep poison, Moranth munitions, communication crystal, cloak of resistance +3, ring of protection +2"
L=dict(cloak=3,defl=2)
lts=[
dict(L,div="Lt I",name="Osmund Tarrow (Quavein's lieutenant)",classes=[("cleric",12)],class_line="Cleric 12 (Trickery / Death; the Storm King's office, quiet face)",
 base=B(14,10,14,10,17,12),bumps=dict(wis=3),items=dict(wis=4,str=2),suit="Stalker",suit_line="Stalker suit (Forgedeep dwarven). Brass censer: no sockets (rolled).",
 attacks=[dict(name="brass censer on a chain (light flail stats, signature piece)",stat="str",mod=1,dice="1d8",note="smokes on a hit: the target is dazzled 1 round (Fort DC 17 negates; technique)")],
 features=WRIT+" Trickery domain: Bluff, Disguise and Hide as class skills. Death domain: death touch 1/day (12d6; if the total equals or exceeds the target's current HP, it dies). Turn undead 4/day.",
 casting="Divine caster level 12; save DC 17 + spell level (Wis 24). Domain spells: *disguise self, invisibility, nondetection, death ward, slay living, mislead, destruction*. Core list: *silence, hold person, dispel magic, greater command, harm, heal, blade barrier*.",
 feats="Combat Casting, Extra Turning, Improved Initiative, Quicken Spell, Weapon Focus (flail).",
 skills="Concentration +17, Bluff +12, Knowledge (religion) +15, Sense Motive +13, Hide +6.",
 kit=EE+"; periapt of Wisdom +4 (throat), belt of giant strength +2. The Bursar's spare bead-cord.",
 tactics="Walks behind Quavein and keeps him standing. Smokes the room with the censer, then slay living on whatever Quavein has marked in the book.",
 g_skill_bonus=3,g_skill_name="Flail",g_adv="Combat Reflexes; Clerical Investment (the Storm King's office); Power Investiture 3; Fearlessness 1",
 g_skills="Theology-15, Acting-13, Observation-13, Accounting-12",g_dis="Sense of Duty (Quavein); Secret (serves an office its holder doesn't know of); Shyness"),
dict(L,div="Lt II",name="Kerra Lisle (Hadda's lieutenant)",classes=[("wizard",14)],class_line="Wizard 14 (transmuter)",
 base=B(10,16,14,17,10,12),bumps=dict(int=3),items=dict(int=4,dex=2),suit="Stalker",suit_line="Stalker suit, mage variant (pure Veil austerity). Duelling rapier: no sockets (rolled).",
 attacks=[dict(name="duelling rapier (signature piece)",stat="dex",mod=1,dice="1d6",dstat="str",note="18–20; Weapon Finesse; *Tenser's transformation* when Hadda wants a second who can actually fight")],
 features=WRIT+" Transmuter: *haste, polymorph, transformation* are her stock. Hadda's second at every duel: she holds the line, calls the time and counts paces.",
 casting="Arcane caster level 14; save DC 17 + spell level (Int 24). Core list: *haste, slow, polymorph, baleful polymorph, disintegrate, Tenser's transformation, transmute rock to mud, stoneskin, dimension door, shield*.",
 feats="Scribe Scroll, Weapon Finesse, Spell Focus (transmutation), Quicken Spell, Extend Spell, Combat Casting, Improved Initiative.",
 skills="Concentration +19, Spellcraft +24, Knowledge (arcana) +24, Tumble +10.",
 kit=EE+"; headband of intellect +4, Evening's Edge of captain's grade (+2 Dex woven in), amulet of natural armor +2. Spellbook in a slim case.",
 tactics="*Haste* on Hadda, *slow* on the opponent's side, then the rapier at Hadda's flank. Counts paces aloud so Hadda never has to look.",
 g_skill_bonus=4,g_skill_name="Rapier",g_adv="Combat Reflexes; Magery 5; Fencing reflexes (Enhanced Parry 1)",
 g_skills="Thaumatology-17, Fast-Draw (rapier)-14, Savoir-Faire (dueling)-15",g_dis="Sense of Duty (Hadda); Honesty (keeps the rules of a duel); Overconfidence"),
dict(L,div="Lt III",name="Wenna Sorrel (Tarvash's lieutenant)",classes=[("wizard",14)],class_line="Wizard 14 (enchanter)",
 base=B(12,14,14,17,12,14),bumps=dict(int=3),items=dict(int=4,con=2),suit="Stalker",suit_line="Stalker suit, mage variant (Bloodaxe Nordic). Short hatchet: no sockets (rolled).",
 attacks=[dict(name="short hatchet (handaxe stats, signature piece)",stat="str",mod=1,dice="1d6",note="×3; carried in the same belt loop as her wand")],
 features=WRIT+" Enchanter: *charm, dominate, confusion*. Tarvash's first find, pressed off a Luskan quay. Chews a reed.",
 casting="Arcane caster level 14; save DC 17 + spell level, 19 + spell level for enchantment (Spell Focus, Greater Spell Focus). Core list: *dominate person, mass suggestion, confusion, hold monster, feeblemind, greater invisibility, dimension door, shield, dispel magic*.",
 feats="Scribe Scroll, Spell Focus (enchantment), Greater Spell Focus (enchantment), Quicken Spell, Combat Casting, Improved Initiative, Persuasive.",
 skills="Concentration +19, Spellcraft +24, Bluff +14, Diplomacy +12, Climb +6.",
 kit=EE+"; headband of intellect +4, amulet of health +2.",
 tactics="Dominates the gate-captain before Tarvash drops off the roof. Hatchet for whoever the charm doesn't take.",
 g_skill_bonus=3,g_skill_name="Axe/Mace",g_adv="Combat Reflexes; Magery 5; Voice; Smooth Operator",
 g_skills="Thaumatology-16, Fast-Talk-15, Streetwise-14, Seamanship-11",g_dis="Sense of Duty (Tarvash's strays); Secret (her life on the quay); Impulsiveness"),
dict(L,div="Lt IX",name="Faelith Ammarin (Mercy's lieutenant)",classes=[("fighter",14)],class_line="Fighter 14 (shield fighter)",
 base=B(16,14,14,10,12,10),race=dict(dex=2,con=-2),bumps=dict(str=3),items=dict(str=4,con=2),suit="Stalker",suit_line="Stalker suit (Forgedeep dwarven). Darkwood tower shield: no sockets (rolled).",
 attacks=[dict(name="darkwood tower shield, edged in iron (signature piece; bashed as a heavy shield, affinity translation)",stat="str",mod=0,dice="1d8",note="Improved Shield Bash keeps the shield's AC; bull rush on a hit (technique)"),
          dict(name="longsword",stat="str",mod=2,dice="1d8",dbonus=2,note="19–20; Weapon Specialization")],
 features=WRIT+" Low-light vision (elf). The tower shield gives total cover when planted and +4 shield AC otherwise; the stat block counts it at +4. Sings off-key when Mercy goes quiet.",
 feats="Improved Shield Bash, Shield Charge, Shield Slam, Power Attack, Improved Bull Rush, Cleave, Weapon Focus (longsword), Weapon Specialization (longsword), Combat Reflexes, Improved Initiative, Tower Shield Proficiency, Iron Will.",
 skills="Climb +16, Intimidate +10, Jump +14, Listen +6, Spot +6.",
 kit=EE+"; belt of giant strength +4, amulet of health +2.",
 tactics="Plants the shield in the doorway Mercy is about to come through, then walks it forward and knocks people over.",
 g_skill_bonus=5,g_skill_name="Shield",shield_ac=4,g_adv="Combat Reflexes; Enhanced Block 1; Fit; Night Vision 3",
 g_skills="Broadsword-18, Singing-9, Tactics-12",g_dis="Sense of Duty (Mercy); Honesty; Tone-deaf (Odious habit, mild)"),
dict(L,div="Lt X",name="Patience Haskett (Zaheda's lieutenant)",classes=[("fighter",13)],class_line="Fighter 13 (flail)",
 base=B(17,14,14,10,10,8),race=dict(dex=2,int=2,cha=-2),bumps=dict(str=3),items=dict(str=4,con=2),suit="Stalker",suit_line="Stalker suit (Bloodaxe Nordic). Two-headed flail: no sockets (rolled).",
 attacks=[dict(name="two-headed heavy flail (dire flail stats, double weapon, signature piece), main head",stat="str",mod=-1,dice="1d8",dbonus=2,note="two-weapon with a double weapon (−2/−2), offset by Weapon Focus; Weapon Specialization; trip and disarm"),
          dict(name="dire flail, second head",stat="str",mod=-1,dice="1d8",dmult=0.5,dbonus=2,full=False,note="off-hand attacks per Improved Two-Weapon Fighting")],
 features=WRIT+" Darkvision 60 ft; *darkness* 1/day; resist cold, fire and electricity 5 (tiefling). He is learning Zaheda's cipher, and she has not stopped him.",
 feats="Exotic Weapon Proficiency (dire flail), Two-Weapon Fighting, Improved Two-Weapon Fighting, Weapon Focus (dire flail), Weapon Specialization (dire flail), Improved Trip, Combat Expertise, Improved Disarm, Power Attack, Combat Reflexes, Improved Initiative.",
 skills="Climb +14, Intimidate +8, Decipher Script +4 (her cipher, in progress), Ride +6.",
 kit=EE+"; belt of giant strength +4, amulet of health +2.",
 tactics="Taps three times with his tail and moves. Trips the target for the tiger.",
 g_skill_bonus=5,g_skill_name="Flail",g_adv="Combat Reflexes; Ambidexterity; Night Vision 4; Resistant (heat, cold)",
 g_skills="Cryptography-9, Climbing-13, Intimidation-10",g_dis="Sense of Duty (Zaheda); Curious (the cipher); Odious habit (tail-tapping)"),
dict(L,div="Lt XI",name="Rhun Talbridge (Ysmay's lieutenant)",classes=[("fighter",13)],class_line="Fighter 13 (pollaxe)",
 base=B(17,13,14,10,12,10),bumps=dict(str=3),items=dict(str=4,con=2),suit="Stalker",suit_line="Stalker suit (Calishite-Amnian). Pollaxe: **one strange socket** (rolled; filled in the item pass).",
 attacks=[dict(name="pollaxe (halberd stats, signature piece)",stat="str",mod=1,dice="1d10",dmult=1.5,dbonus=2,note="×3; reach-free (held short); Weapon Specialization; trip with the hook")],
 features=WRIT+" Low-light vision (half-elf). Hands Ysmay the water flask before she asks, and stands on her bright-light side.",
 feats="Weapon Focus (halberd), Weapon Specialization (halberd), Power Attack, Cleave, Great Cleave, Improved Trip, Combat Expertise, Combat Reflexes, Improved Initiative, Iron Will, Blind-Fight.",
 skills="Climb +12, Intimidate +8, Sense Motive +6, Spot +8.",
 kit=EE+"; belt of giant strength +4, amulet of health +2. Ysmay's water flask.",
 tactics="Keeps the light behind Ysmay and the enemy in it. Hooks a leg, and she finishes.",
 g_skill_bonus=5,g_skill_name="Polearm",g_adv="Combat Reflexes; Fit; High Pain Threshold",
 g_skills="Body Language-12, First Aid-11, Tactics-12",g_dis="Sense of Duty (Ysmay); Secret (her eyes, which he has noticed); Honesty"),
dict(L,div="Lt XII",name="Edwyn Coldry (Ilvaera's lieutenant)",classes=[("wizard",13)],class_line="Wizard 13 (abjurer)",
 base=B(10,12,14,17,12,10),age=SEAS,bumps=dict(int=3),items=dict(int=4,con=2),suit="Stalker",suit_line="Stalker suit, mage variant (Forgedeep dwarven). Mail mitten: no sockets (rolled).",
 attacks=[dict(name="mail mitten (spiked gauntlet stats, signature piece)",stat="str",mod=1,dice="1d4",note="the spell-burned hand; a touch spell delivered through it counts as armed")],
 features=WRIT+" Abjurer: *dispel magic, greater dispel magic, globe of invulnerability, dimensional anchor*. He cleans up after Ilvaera: wards the scene, dispels the traces, and hums hymns from a faith he left.",
 casting="Arcane caster level 13; save DC 17 + spell level (Int 25). Core list: *greater dispel magic, globe of invulnerability, dimensional anchor, mind fog, nondetection, wall of force, mislead, shield, dimension door*.",
 feats="Scribe Scroll, Spell Focus (abjuration), Improved Counterspell, Quicken Spell, Combat Casting, Improved Initiative, Silent Spell.",
 skills="Concentration +18, Spellcraft +23, Knowledge (arcana) +23, Knowledge (religion) +11.",
 kit=EE+"; headband of intellect +4, amulet of health +2.",
 tactics="Counterspells the one caster who could stop Ilvaera, then erases the evidence afterward.",
 g_skill_bonus=2,g_skill_name="Brawling",g_adv="Combat Reflexes; Magery 5; Magic Resistance 2",
 g_skills="Thaumatology-16, Counterspelling-17, Theology-13, Forensics (magical)-14",g_dis="Guilt Complex (the faith he left); Sense of Duty (Ilvaera); Secret (what he has cleaned up)"),
dict(L,div="Lt XIII",name="Ashavel Oriym (Dace's lieutenant)",classes=[("swordsage",14)],class_line="Swordsage 14 (Desert Wind, Setting Sun)",
 base=B(12,17,14,10,15,10),race=dict(dex=2,con=-2),bumps=dict(dex=2,wis=1),items=dict(dex=4,wis=2),suit="Strider",suit_line="Strider suit (Forgedeep dwarven), light armor for the swordsage AC bonus. Iron war-fans: **one shard socket** (rolled; filled in the item pass).",
 class_ac=4,
 attacks=[dict(name="iron war-fans, razored ribs (dagger stats, a pair, signature piece), main",stat="dex",mod=0,dice="1d4",note="19–20; Weapon Finesse; two light weapons (−2/−2) offset by Weapon Focus"),
          dict(name="war-fan, off hand",stat="dex",mod=0,dice="1d4",dmult=0.5,full=False)],
 features=WRIT+" Low-light vision (elf). Initiator level 14: maneuvers to 7th level. Desert Wind: *burning blade, fan the flames, dragon's flame, inferno blade*. Setting Sun: *feigned opening, comet throw*. Stance: *flashing sun*. Fans herself before a fight in any weather. Swordsage AC bonus (Wis +4) applies: the Strider counts as light armor.",
 feats="Weapon Finesse, Two-Weapon Fighting, Weapon Focus (dagger), Combat Reflexes, Desert Fire, Improved Initiative.",
 skills="Tumble +21, Jump +18, Concentration +17, Perform (dance) +12.",
 kit=EE+"; Evening's Edge of captain's grade (+4 Dex woven in), periapt of Wisdom +2 (throat).",
 tactics="Dances inside Dace's reach, burning blade on both fans, while he takes the challenge.",
 g_skill_bonus=5,g_skill_name="Main-Gauche (war-fan, tessenjutsu)",g_adv="Combat Reflexes; Ambidexterity; Trained by a Master; Night Vision 3",
 g_skills="Dancing-15, Acrobatics-15",g_dis="Sense of Duty (Dace); Odious habit (fans herself); Impulsiveness"),
]
json.dump(lts,open("menagerie_lieutenants_data.json","w"),indent=1)
