#!/usr/bin/env python3
"""Fetch a YouTube video's public metadata and transcript.

Runs inside .github/workflows/video-transcript.yml on a GitHub runner because
the Claude Code sandbox cannot reach YouTube. Utility only: it prints what it
finds between clear markers and writes the same to --out-dir. It never writes
canon, mechanics, or anything under reference/ or mirrors/.

Source order: yt-dlp, then public Piped and Invidious API mirrors, then
YouTube's oEmbed endpoint (title and channel only). Transcript comes from
whichever source supplied captions, else youtube-transcript-api.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request

UA = "the-new-path-engine video_transcript.py (+https://github.com/CFhacky/the-new-path-engine)"
PIPED = ["https://pipedapi.kavin.rocks", "https://pipedapi.adminforge.de", "https://api.piped.yt"]
INVIDIOUS = ["https://yewtu.be", "https://inv.nadeko.net", "https://invidious.nerdvpn.de"]


def fmt_time(seconds: float) -> str:
    seconds = int(seconds or 0)
    return f"{seconds // 60:02d}:{seconds % 60:02d}"


def http_json(url: str, timeout: int = 20):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def http_text(url: str, timeout: int = 20) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8", "replace")


def parse_vtt_text(text: str) -> list[dict]:
    lines: list[dict] = []
    last = None
    ts = re.compile(r"^(\d\d):(\d\d):(\d\d)\.(\d{3}) --> ")
    start = 0.0
    for raw in text.splitlines():
        m = ts.match(raw)
        if m:
            h, mi, s, ms = (int(x) for x in m.groups())
            start = h * 3600 + mi * 60 + s + ms / 1000
            continue
        if not raw or raw.startswith(("WEBVTT", "Kind:", "Language:", "NOTE")) or re.fullmatch(r"\d+", raw.strip()):
            continue
        t = re.sub(r"<[^>]+>", "", raw).strip()
        if t and t != last:
            lines.append({"start": start, "duration": 0.0, "text": t})
            last = t
    return lines


def dump_meta_ytdlp(video_id: str) -> dict:
    url = f"https://www.youtube.com/watch?v={video_id}"
    proc = subprocess.run(
        ["yt-dlp", "--skip-download", "--dump-single-json", "--no-warnings", url],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        print(f"yt-dlp metadata failed: {proc.stderr.strip()[:600]}", file=sys.stderr)
        return {}
    return json.loads(proc.stdout)


def piped_meta(video_id: str) -> tuple[dict, list[dict]]:
    for base in PIPED:
        try:
            d = http_json(f"{base}/streams/{video_id}")
        except Exception as exc:  # noqa: BLE001 - try the next mirror
            print(f"piped {base} failed: {exc!r}"[:300], file=sys.stderr)
            continue
        meta = {
            "title": d.get("title"), "channel": d.get("uploader"), "upload_date": d.get("uploadDate"),
            "duration_string": fmt_time(d.get("duration")), "view_count": d.get("views"),
            "like_count": d.get("likes"), "categories": [d.get("category")] if d.get("category") else None,
            "tags": d.get("tags"),
            "chapters": [{"start_time": c.get("start"), "title": c.get("title")} for c in d.get("chapters") or []],
            "description": d.get("description"),
        }
        lines: list[dict] = []
        subs = sorted(d.get("subtitles") or [], key=lambda x: (not str(x.get("code", "")).startswith("en"), bool(x.get("autoGenerated"))))
        for sub in subs[:1]:
            try:
                lines = parse_vtt_text(http_text(sub["url"]))
            except Exception as exc:  # noqa: BLE001
                print(f"piped subtitle fetch failed: {exc!r}"[:300], file=sys.stderr)
        return meta, lines
    return {}, []


def invidious_meta(video_id: str) -> tuple[dict, list[dict]]:
    for base in INVIDIOUS:
        try:
            d = http_json(f"{base}/api/v1/videos/{video_id}")
        except Exception as exc:  # noqa: BLE001 - try the next mirror
            print(f"invidious {base} failed: {exc!r}"[:300], file=sys.stderr)
            continue
        meta = {
            "title": d.get("title"), "channel": d.get("author"), "upload_date": d.get("publishedText"),
            "duration_string": fmt_time(d.get("lengthSeconds")), "view_count": d.get("viewCount"),
            "like_count": d.get("likeCount"), "categories": [d.get("genre")] if d.get("genre") else None,
            "tags": d.get("keywords"), "chapters": None, "description": d.get("description"),
        }
        lines: list[dict] = []
        caps = sorted(d.get("captions") or [], key=lambda c: not str(c.get("language_code", "")).startswith("en"))
        for cap in caps[:1]:
            try:
                lines = parse_vtt_text(http_text(base + cap["url"]))
            except Exception as exc:  # noqa: BLE001
                print(f"invidious caption fetch failed: {exc!r}"[:300], file=sys.stderr)
        return meta, lines
    return {}, []


def oembed(video_id: str) -> dict:
    q = urllib.parse.quote(f"https://www.youtube.com/watch?v={video_id}", safe="")
    try:
        d = http_json(f"https://www.youtube.com/oembed?url={q}&format=json")
        return {"title": d.get("title"), "channel": d.get("author_name")}
    except Exception as exc:  # noqa: BLE001
        print(f"oembed failed: {exc!r}"[:300], file=sys.stderr)
        return {}


def transcript_via_api(video_id: str, langs: list[str]) -> list[dict]:
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
        fetched = YouTubeTranscriptApi().fetch(video_id, languages=langs)
        return [{"start": s.start, "duration": s.duration, "text": s.text} for s in fetched]
    except Exception as exc:  # noqa: BLE001
        print(f"youtube-transcript-api failed: {exc!r}"[:600], file=sys.stderr)
        return []


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--video-id", required=True)
    ap.add_argument("--languages", default="en,en-US,en-GB")
    ap.add_argument("--out-dir", default="transcript_out")
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    langs = [x.strip() for x in args.languages.split(",") if x.strip()]

    lines: list[dict] = []
    meta = dump_meta_ytdlp(args.video_id)
    if not meta.get("title"):
        meta, lines = piped_meta(args.video_id)
    if not meta.get("title"):
        meta, lines = invidious_meta(args.video_id)
    if not meta.get("title"):
        meta = oembed(args.video_id)

    fields = ("id", "title", "channel", "uploader", "upload_date", "duration_string",
              "view_count", "like_count", "categories", "tags", "chapters", "description")
    keep = {k: meta.get(k) for k in fields}
    keep["id"] = args.video_id
    with open(os.path.join(args.out_dir, "metadata.json"), "w", encoding="utf-8") as fh:
        json.dump(keep, fh, indent=2, ensure_ascii=False)

    print("=== VIDEO METADATA BEGIN ===")
    for k in fields[:-2]:
        print(f"{k}: {keep.get(k)}")
    if keep.get("chapters"):
        print("chapters:")
        for ch in keep["chapters"]:
            print(f"  {fmt_time(ch.get('start_time', 0))}  {ch.get('title')}")
    print("description:")
    print(keep.get("description") or "(none)")
    print("=== VIDEO METADATA END ===")

    lines = lines or transcript_via_api(args.video_id, langs)
    print("=== TRANSCRIPT BEGIN ===")
    if not lines:
        print("(no transcript available)")
    else:
        with open(os.path.join(args.out_dir, "transcript.txt"), "w", encoding="utf-8") as fh:
            for seg in lines:
                row = f"[{fmt_time(seg['start'])}] {seg['text']}"
                print(row)
                fh.write(row + "\n")
    print("=== TRANSCRIPT END ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
